version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
  networks:
      - proxy
  labels:
      - traefik.http.routers.web.rule=Host(`reserv.jitsi-mathu.de`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=lets-encrypt
      - traefik.port=80
