version: "3.6"
services:
  reserver_v1.1:
    build: .
    networks:
      - proxy
      - reservation_reserver-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reserv.entrypoints=http"
      - "traefik.http.routers.reserv.rule=Host(`kon.jitsi-mathu.de`)"     ### Bitte anpassen wie im Schritt 1 ###
      - "traefik.http.middlewares.reserv-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.reserv.middlewares=reserv-https-redirect"
      - "traefik.http.routers.reserv-secure.entrypoints=https"
      - "traefik.http.routers.reserv-secure.rule=Host(`kon.jitsi-mathu.de`)"    ### Bitte anpassen wie im Schritt 1 ###
      - "traefik.http.routers.reserv-secure.tls=true"
      - "traefik.http.routers.reserv-secure.tls.certresolver=http"
      - "traefik.http.routers.reserv-secure.service=reserver-v1-1-reservation"
      - "traefik.docker.network=proxy"

networks:
  reservation_reserver-net:
    external: true
  proxy:
    external: true
